version: "3.8"
services:
  db:
    container_name: postgres_db
    image: postgres:15
    restart: always
    command: postgres -c 'max_connections=250'
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    ports:
      - ${PGPORT}:${PGPORT}
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local

